config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "landing#index"
  
  resources :animals do 
    collection do 
      post :contact
      get :mine
    end
    resources :file_uploads, only: [:new, :create, :destroy]
  end
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  has_many_attached :files 
  belongs_to :user
  
  extend Enumerize
  enumerize :kind, in: [:dog, :cat, :other], scope: true
  enumerize :gender, in: [:male, :female], scope: true
  enumerize :size, in: [:small, :mid, :big], scope: true
  enumerize :city, in: [:taquara, :igrejinha, :parobé, :rolante, :sapiranga], scope: true
  
  scope :neutered, -> (neutered) { where neutered: neutered }
  scope :vaccinated, -> (vaccinated) { where vaccinated: vaccinated }
  #TODO age scope
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :omniauthable, 
  :omniauth_providers => [:facebook]
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      #user.email = auth.info.email
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.first_name   # assuming the user model has a name
      user.surname = auth.info.last_name
      user.link = auth.extra.raw_info.link
      user.image = auth.info.image
      user.birthday = auth.extra.raw_info.birthday
      #user.image = auth.info.image # assuming the user model has an image
    end
  end
  has_many :animals  
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  protect_from_forgery with: :null_session, only: :contact
    def index 
      #@animals = Animal.all
            
      @animals = Animal.where(nil) # creates an anonymous scope
      if params[:filter]
        @animals = @animals.with_kind(filter_params[:kind]) if filter_params[:kind].present?
        @animals = @animals.with_gender(filter_params[:gender]) if filter_params[:gender].present?
        @animals = @animals.with_size(filter_params[:size]) if filter_params[:size].present?
        @animals = @animals.neutered(filter_params[:neutered]) if filter_params[:neutered].present?
        @animals = @animals.vaccinated(filter_params[:vaccinated]) if filter_params[:vaccinated].present?
        @animals = @animals.with_city(filter_params[:city]) if filter_params[:city].present?
      end
      #byebug

    end
    def mine 
      @animals = current_user.animals.all
    end
    def show 
        @animal = Animal.find(params[:id])
    end
    def edit
        @animal = Animal.find(params[:id])
    end
    def new
      @animal = Animal.new
    end
    def create
      @animal = Animal.new(animal_params)
      respond_to do |format|
        if @animal.save(animal_params)
          format.html { redirect_to edit_animal_path(@animal), notice: 'Device was successfully updated.' }
          format.json { render :show, status: :ok, location: @animal }
        else
          format.html { render :edit }
          format.json { render json: @animal.errors, status: :unprocessable_entity }
        end
      end
    end
    def update
      @animal = Animal.find(params[:id])
        respond_to do |format|
          if @animal.update(animal_params)
            format.html { redirect_to @animal, notice: 'Device was successfully updated.' }
            format.json { render :show, status: :ok, location: @animal }
          else
            format.html { render :edit }
            format.json { render json: @animal.errors, status: :unprocessable_entity }
          end
        end
      end
      def destroy
        @animal = Animal.find(params[:id])
        @animal.destroy
        respond_to do |format|
          format.html { redirect_to mine_animals_url, notice: 'Animal was successfully destroyed.' }
        end
      end
      def contact
        contact_data = {
          name: params[:name_contact],
          phone: params[:phone_contact],
          email_from: params[:email_contact],
          message: params[:message_contact],
          animal_id: params[:animal_id]
        }
        AdoptionMailer.interested(contact_data).deliver
        redirect_to animal_path(params[:animal_id])
      end
      private 
      def animal_params
        params.require(:animal).permit(:name, :city, :kind, :breed, :gender, :birth, :size, :neutered, :vaccinated, :description, :user_id)
      end
      def filter_params
        params.require(:filter).permit(:kind, :city, :breed, :gender, :size, :neutered, :vaccinated)
      end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
def new
  @animal = Animal.find(params[:animal_id])
end

def create
  @animal = Animal.find(params[:animal_id])
  @animal.files.attach(params[:animal][:files])
  redirect_to edit_animal_path(@animal)
end
def destroy
  @animal = Animal.find(params[:animal_id])
  @animal.files.find(params[:id]).purge
  redirect_to edit_animal_path(@animal)
end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index 
      @animals = Animal.all
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/views/animals/_edit_form.html.erb
<%= simple_form_for @animal, defaults: { input_html: { class: 'form-horizontal' } } do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %> 
  <div class="form-group row">
    <div class="col-sm-6">
      <%= f.input :name, required: true,  class: "form-control" %>
    </div>
    <div class="col-sm-6">
      <%= f.input :breed, required: true,  class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-6">
      <%= f.input :kind, required: true,  class: "form-control" %>
    </div>    
    <div class="col-sm-6">
      <%= f.input :city, required: true,  class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-6">
      <%= f.input :gender, required: true,  class: "form-control" %>
    </div>
    <div class="col-sm-6">
      <%= f.input :size, required: true,  class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-6">
      <%= f.input :vaccinated, required: false,  class: "form-control" %>
    </div>
    <div class="col-sm-6">
      <%= f.input :neutered, required: false,  class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :birth, class: "col-sm-3 col-form-label" %>
    <div class="col-sm-4">
      <%= f.date_field :birth, required: true,  class: "form-control" %>
    </div>
  </div>
  <%= f.input :description %>
  <%= f.button :submit, 'Salvar', class: "btn btn-success" %>
  <%= link_to 'Excluir animal', animal_path(@animal), method: :delete, data: { confirm: "Tem certeza que deseja excluir este animal?" }, class: 'btn btn-danger' %>
<% end %>

app/views/animals/_form.html.erb
<%= simple_form_for @animal, defaults: { input_html: { class: 'form-horizontal' } } do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %> 
  <div class="form-group row">
    <div class="col-sm-6">
      <%= f.input :name, required: true,  class: "form-control" %>
    </div>
    <div class="col-sm-6">
      <%= f.input :breed, required: true,  class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-6">
      <%= f.input :kind, required: true,  class: "form-control" %>
    </div>    
    <div class="col-sm-6">
      <%= f.input :city, required: true,  class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-6">
      <%= f.input :gender, required: true,  class: "form-control" %>
    </div>
    <div class="col-sm-6">
      <%= f.input :size, required: true,  class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-6">
      <%= f.input :vaccinated, required: false,  class: "form-control" %>
    </div>
    <div class="col-sm-6">
      <%= f.input :neutered, required: false,  class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :birth, class: "col-sm-3 col-form-label" %>
    <div class="col-sm-4">
      <%= f.date_field :birth, required: true,  class: "form-control" %>
    </div>
  </div>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/animals/_search_menu.html.erb
 <!-- Styles -->
      <style>
     
			/*
			#hd h1 { font-size: 48px; text-transform: uppercase; letter-spacing: 3px; }
			h2 { font-size: 152% }
			h3, h4 { font-size: 122%; }
			h1, h2, h3, h4 { color: #333; }
			p { font-size: 100%; line-height: 18px; padding-right: 3em; }
			
			
			strong { font-weight: bold; }
			li { line-height: 24px; solid #ccc; }
			p.enlarge { font-size: 144%; line-height: 24px; }
			p.enlarge span { color: #000 }
			.contact-info { margin-top: 7px; }
			.first h2 { font-style: italic; } */
			
			.line{border-bottom: 1px solid #C0C0C0; }
		  .menu{line-height: 24px; font-size: 160%; color: #000000; font-family: Helvetica;}
		  .lista{list-style: none;}
		  .item{line-height: 24px; text-decoration: none !important; margin-right: 10px; font-size: 130%; color: #000000; padding: 20;}
      </style>

      <div class="col-md-2">
       <%= simple_form_for :filter, :url => animals_path, html: { novalidate: true }, :method => :get do |f| %>
          <%= f.input :kind,     as: :radio_buttons, collection: [['Cachorro', 'dog'], ['Gato', 'cat'],['Outros','other']], :required => false %>
          <%= f.input :gender,     as: :radio_buttons, collection: [['Macho', 'male'], ['Fêmea', 'female']], :required => false %>
          <%= f.input :size,     as: :radio_buttons, collection: [['Pequeno', 'small'], ['Médio', 'mid'],['Grande','big']], :required => false %>
          <%= f.input :neutered,     as: :radio_buttons, collection: [['Não', '0'], ['Sim', '1']], :required => false %>
          <%= f.input :vaccinated,     as: :radio_buttons, collection: [['Não', '0'], ['Sim', '1']], :required => false %>
					<%= f.input :city,:collection => Animal.city.values,:label => "Cidade" ,:include_blank => true, :required => false %>
          <%= button_tag(type: 'submit', class: "btn btn-success btn-block btn-lg") do %>
              <i class="fa fa-search"></i> 
              Filtrar
            <% end %>
        <% end %>
    </div>

app/views/animals/edit.html.erb
<style>
  /*
			#hd h1 { font-size: 48px; text-transform: uppercase; letter-spacing: 3px; }
			h2 { font-size: 152% }
			h3, h4 { font-size: 122%; }
			h1, h2, h3, h4 { color: #333; }
			p { font-size: 100%; line-height: 18px; padding-right: 3em; }
			
			
			strong { font-weight: bold; }
			li { line-height: 24px; solid #ccc; }
			p.enlarge { font-size: 144%; line-height: 24px; }
			p.enlarge span { color: #000 }
			.contact-info { margin-top: 7px; }
			.first h2 { font-style: italic; } */

  /*.line{border-bottom: 1px solid #C0C0C0; }
		  .menu{line-height: 24px; font-size: 160%; color: #000000; font-family: Helvetica;}
		  .lista{list-style: none;}
		  .item{line-height: 24px; text-decoration: none !important; margin-right: 10px; font-size: 130%; color: #000000; padding: 20;}
		  .cadastro1{background: #f5f5f5; border-style: solid; border-width: 1px; border-color: #A9A9A9;}*/
  .cadastro {
    background: #f5f5f5;
  }
</style>

<div class="cadastro col-xs-6 col-md-12">
  <div class="cadastro">
    <h2 style="text-align:center;">Editar cadastro do Animal</h2>
    
    <div class="well col-md-12" style="//margin-top:50px;">
      <h3>Imagens</h3>
      <div class="row">
        <% @animal.files.each do |picture| %>
        <div class="col-xs-6 col-md-2">
          <a href="<%= url_for(picture) %>" target="_blank" class="thumbnail">
            <img src="<%= url_for(picture.variant(combine_options: { resize: " 145x145", extent: "145x145" ,
              background: "white" , gravity: "center" })) %>" alt="
            <%= picture.filename  %>" class="img-responsive" style="max-height:150px;">
          </a>
          <div class="actions" style="text-align:center">
            <%= link_to "Remover", animal_file_upload_path(@animal, picture), method: :delete, data: { confirm: "Tem certeza?" }, class: 'btn btn-danger' %>
          </div>
          <br>
        </div>
        <% end %>
      </div>
      <h4 class="progress" style="display: none">Fazendo upload
        <span class="progress_count"></span>% concluido</h4>
      <%= form_with model: @animal, url: animal_file_uploads_path(@animal),
          method: :post, id: "upload_file", remote: true do |f| %>
      <%= f.file_field :files, multiple: true, direct_upload: true, :class => "btn" %>
      <br>
      <div class="col-xs-6 col-md-4" style="padding:0px;">
        <%= f.submit 'Clique para enviar as imagens', :class => "btn btn-success" %>
      </div>
      <% end %>
    </div>
    
    <br>
    <div class="col-md-8  col-md-offset-2" style="margin-top:50px;">
      <%= render 'edit_form' %>
      <br>
      <div class="col-xs-6 col-md-4">
        <%#= link_to "Excluir animal", animal_path(@animal), method: :delete, data: { confirm: "Tem certeza que deseja excluir este animal?" }, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>

</div>

app/views/animals/index.html.erb
<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

  <!-- Three columns of text below the carousel -->
  <div class="row">
  <%= render 'search_menu' %>
    <div class="col-md-10">
      <% @animals.each do |animal| %>        
        <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <img alt="100%x200" data-src="holder.js/100%x200" style="height: 200px; width: 100%; display: block;" src="<%= url_for(animal.files.first.variant(combine_options: { resize: "275x200^", extent: "275x200", background: "grey", gravity: "center"})) if animal.files.attached? %>"
            data-holder-rendered="true">
          <div class="caption">
            <h3><%= animal.name %></h3>
            <p><%= animal.description %></p>
            <p class="text-center">
              <a href="<%= animal_path(animal) %>" class="btn btn-info" role="button">Visualizar</a>
            </p>
          </div>
        </div>
      </div>
      <% end %>
     

    </div>

  </div>
  <!-- /.row -->


 
</div>
<!-- /.container -->

app/views/animals/mine.html.erb
<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

  <!-- Three columns of text below the carousel -->
  <div class="row">
  <%= render 'search_menu' %>
    <div class="col-md-10">
      <% @animals.each do |animal| %>        
        <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <img alt="100%x200" data-src="holder.js/100%x200" style="height: 200px; width: 100%; display: block;" src="<%= url_for(animal.files.first.variant(combine_options: { resize: "275x200^", extent: "275x200", background: "grey", gravity: "center"})) if animal.files.attached?  %>"
            data-holder-rendered="true">
          <div class="caption">
            <h3><%= animal.name %></h3>
            <p><%= animal.description %></p>
            <p class="text-center">
              <a href="<%= animal_path(animal) %>" class="btn btn-info" role="button">Visualizar</a>
              <a href="<%= edit_animal_path(animal) %>" class="btn btn-success" role="button">Editar</a>
            </p>
          </div>
        </div>
      </div>
      <% end %>
     

    </div>

  </div>
  <!-- /.row -->


 
</div>
<!-- /.container -->

app/views/animals/new.html.erb
<style>
     
			/*
			#hd h1 { font-size: 48px; text-transform: uppercase; letter-spacing: 3px; }
			h2 { font-size: 152% }
			h3, h4 { font-size: 122%; }
			h1, h2, h3, h4 { color: #333; }
			p { font-size: 100%; line-height: 18px; padding-right: 3em; }
			
			
			strong { font-weight: bold; }
			li { line-height: 24px; solid #ccc; }
			p.enlarge { font-size: 144%; line-height: 24px; }
			p.enlarge span { color: #000 }
			.contact-info { margin-top: 7px; }
			.first h2 { font-style: italic; } */
			
			/*.line{border-bottom: 1px solid #C0C0C0; }
		  .menu{line-height: 24px; font-size: 160%; color: #000000; font-family: Helvetica;}
		  .lista{list-style: none;}
		  .item{line-height: 24px; text-decoration: none !important; margin-right: 10px; font-size: 130%; color: #000000; padding: 20;}
		  .cadastro1{background: #f5f5f5; border-style: solid; border-width: 1px; border-color: #A9A9A9;}*/
		  .cadastro{background: #f5f5f5;}
</style>

<div class="cadastro col-md-12">
  <div class="cadastro">
      <h2 style="text-align:center;">Cadastro do Animal</h2>
        <div class="col-md-2"> </div>
        <div class="col-md-8">
           <%= render 'form' %>
           <br>
        </div>
  </div>
</div>

app/views/animals/show.html.erb
<div class="container">
  <div class="row-fluid">
    <div class="col-lg-8">
      <!-- 2. Add images to <div class="fotorama"></div>. -->
      <style>
        .fotorama1522617869150 .fotorama__nav--thumbs .fotorama__nav__frame {
          padding: 2px;
          height: 64px
        }

        .fotorama1522617869150 .fotorama__thumb-border {
          height: 60px;
          border-width: 2px;
          margin-top: 2px
        }
      </style>
      <div class="fotorama" data-nav="thumbs" data-width="100%" data-ratio="800/600" data-thumb-height "46">
        <% @animal.files.each do |file| %>
          <a href="<%= file.filename %>">
            <img src="<%= url_for(file.variant(combine_options: { resize: "800x600^", extent: "800x600", background: "grey", gravity: "center"})) %>">
          </a>
        <% end %>
      </div>
      
      <div class="row-fluid property-info">
        <h4>
          <%= @animal.name %>
        </h4>

        <p class="description">
          <%= @animal.description %>
        </p>       
      </div>
      <!-- end about property -->
    </div>
    <!-- end span8 -->


    <div class="col-lg-4 col-md-4">
      <!--key features-->
      <h4>Características do animal:</h4>
      <div class="property-info">
        <ul class="property-info">
          <li>
            <strong>Nome:</strong>
            <%= @animal.name %>
          </li>
          <li>
            <strong>Tipo:</strong>
            <%= t("showpage.kind.#{@animal.kind}") %>
          </li>
          <li>
            <strong>Raça:</strong>
            <%= @animal.breed %>
          </li>
          <li>
            <strong>Sexo:</strong>
            <%= t("showpage.gender.#{@animal.gender}") %>
          </li>
          <li>
            <strong>Idade:</strong>
            <%= time_ago_in_words(@animal.birth) %>
          </li>
          <li>
            <strong>Tamanho:</strong>
            <%= t("showpage.size.#{@animal.size}") %>
          </li>
          <li>
            <strong>Castrado:</strong>
            <%= t("showpage.#{@animal.neutered}") %>
          </li>
          <li>
            <strong>Vacinado:</strong>
            <%= t("showpage.#{@animal.vaccinated}") %>
          </li>
          <li>
            <strong>Cidade:</strong>
            <%= t("showpage.#{@animal.city.to_s}") %>
          </li>
        </ul>

        <!--divider-->
        <!-- <div class="divider"></div> -->

        <!--single map-->
        <!-- <h4>Localização:</h4>
                <div id="map_canvas"></div> -->
        <br>
        <!--divider-->
        <div class="divider"></div>
        <!-- contact agent form -->
        <div id="message"></div>
        <form role="form" method="post" action="<%= contact_animals_path %>" id="contactform" autocomplete="off">
          <h3>Contato sobre este animal:</h3>
          <input class="form-control"  type="hidden" name="animal_id" value=<%= @animal.id %>>
          <div class="form-group">
            <input class="form-control" placeholder="Nome" name="name_contact" type="text">
          </div>

          <div class="form-group">
            <input class="form-control"  type="email" placeholder="Email" name="email_contact" type="text">
          </div>

          <div class="form-group">
            <input class="form-control" placeholder="Telefone" name="phone_contact" type="text">
          </div>

          <div class="form-group">
            <textarea class="form-control" rows="6" placeholder="Mensagem" name="message_contact" ></textarea>
          </div>
          <div class="row">
            <div class="col-xs-6 col-md-6">
              <input type="submit" value="Enviar" class="btn btn-success btn-block btn-lg" tabindex="7">
            </div>
          </div>
        </form>

        <!-- end contact agent form -->
      </div>

    </div>
    <!-- end row-fluid -->

  </div>
  <!-- /.row -->





</div>
<!-- /.container -->

app/views/landing/index.html.erb
<!-- Carousel
================================================== -->
<div class="">
 
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <% @animals.each do |animal| %>
      <% if animal.files.attached? %>
      <div class="item">
      <img class="second-slide" src="<%= url_for(animal.files.first.variant(combine_options: { resize: "1140x645^", extent: "1140x645", background: "grey", gravity: "center"})) %>" alt="<%= animal.name %>">
      <div class="container">
        <div class="carousel-caption">
          <h1><%= animal.name %></h1>              
          <p><a class="btn btn-lg btn-primary" href="<%= animal_path(animal) %>" role="button">Visualizar</a></p>
        </div>
      </div>
    </div>
    <% end %> 
   <% end %> 
 
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div><!-- /.carousel -->


<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-lg-4">
      <img class="img-circle" src="https://cdn.icon-icons.com/icons2/653/PNG/512/locate_gps_navigation_pin_point_location_icon-icons.com_59906.png" alt="Generic placeholder image" width="140" height="140">
      <h2>Procure</h2>
      <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="img-circle" src="https://image.flaticon.com/icons/svg/33/33308.svg" alt="Generic placeholder image" width="140" height="140">
      <h2>Conheça</h2>
      <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="img-circle" src="https://image.flaticon.com/icons/svg/26/26129.svg" alt="Generic placeholder image" width="140" height="140">
      <h2>Adote</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
  </div><!-- /.row -->


  

<script>
$(document).on('ready turbolinks:load', function() {
  var $item = $('.item');
  $item.eq(0).addClass('active');
});
</script>
</div><!-- /.container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Adocao</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>
  </body>
  
</html>

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<br>
<div class="container">
<footer class="col-md-12">
  <!--<br>
  <p class="pull-right">
    <a href="#">Back to top</a>
  </p>
  <p>&copy; 2018 &middot;
    <a href="#"></a> &middot;
    <a href="#"></a>
  </p>-->
</footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" style="color:white;" href="/">Projeto Adotar</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="<%= 'active' if current_page?(animals_path) %>"> <a href="<%= animals_path %>">Adotar</a> </li>
                 <% if user_signed_in? %>
                    <li class="<%= 'active' if current_page?(new_animal_path) %>"> <a href="<%= new_animal_path %>">Cadastrar Animal</a> </li>
                    <li class="<%= 'active' if current_page?(mine_animals_path) %>"> <a href="<%= mine_animals_path %>">Meus Animais</a> </li>
                <% end%>
                <li><a href="#contact">Sobre Nós</a></li>               
              </ul>
            <ul class="nav navbar-nav navbar-right"style="padding-top: 10px;padding-right: 10px;">
              <% if user_signed_in? %>
                <ul><a class="btn-sm btn-block btn-social btn-facebook" href="<%= destroy_user_session_path %>" data-method="delete"><span class="glyphicon glyphicon-log-out"></span> Sair</a></ul>
                <% else %>
                <ul>
                  <%= link_to '<span class="fa fa-facebook"></span>Entrar com Facebook'.html_safe, user_facebook_omniauth_authorize_path, class: "btn-sm btn-block btn-social btn-facebook" %>
                </ul>
                <% end%>
            </ul>
            </div>
          </div>
        </nav>

      </div>
    </div>

    <br>
    <br>
    <br>
    <br>